# general
seed: 1
device: 'cuda'
output_path: '/hy-tmp/TF_results_glfm'

# data
data_path: 'data/a_dog_play.mp4'
width: 512
height: 512
latents_path: '/hy-tmp/Inv_Latents/base_glfm/' # should be the same as 'save_dir' arg used in preprocess
n_inversion_steps: 50 # for retrieving the latents of the inversion
n_frames: 400
inversion_prompt: 'A woman is playing with a siberian husky. Tattooed arms.'
# frames of a clip
n_clip_frames: 2
# number of basisi vectors of global frames modeling, modulation factor alpha
gfm_k1: 32
gfm_alpha: 0.6
# number of basisi vectors of local frames modeling, modulation factor beta
lfm_k2: 32
lfm_beta: 1.0

# diffusion
sd_version: '1.5'
guidance_scale: 7.5
n_timesteps: 50
prompt: "A woman is playing with a golden retriever. Normal-skin arms."
negative_prompt: "ugly, blurry, low res, unrealistic, unaesthetic"
batch_size: 100
flow_batch_size: 20

# pnp params -- injection thresholds ∈ [0, 1]
pnp_attn_t: 0.5
pnp_f_t: 0.8
